import type { PollResult, QuestionResult } from "@/lib/supabaseHelpers";
import { formatDateFull } from "@/lib/dateUtils";

// A results record for the minutes. Kept plain and official — a document a
// committee, council or church can attach to a meeting record — rather than a
// branded marketing artefact. jsPDF is imported on demand so it never lands in
// the initial page bundle.

export interface ResultsPdfInput {
  pollTitle: string;
  pollCode: string;
  totalVoters: number;
  isMultiQuestion: boolean;
  results?: PollResult[];
  questionResults?: QuestionResult[];
  generatedAt?: string; // ISO; defaults to now
}

const MARGIN = 48;
const PAGE_W = 595.28; // A4 in pt
const PAGE_H = 841.89;
const CONTENT_W = PAGE_W - MARGIN * 2;
const INK = 17; // near-black
const MUTED = 110;
const RULE = 210;
const BAR_BG = 232;
const BAR_FILL: [number, number, number] = [16, 185, 129]; // emerald

function pct(count: number, total: number): string {
  return total > 0 ? ((count / total) * 100).toFixed(1) : "0.0";
}

// jsPDF's type isn't imported at module load (dynamic import), so the doc is
// typed loosely inside the builder.
type Doc = {
  setFont: (family: string, style?: string) => void;
  setFontSize: (n: number) => void;
  setTextColor: (g: number) => void;
  setDrawColor: (g: number) => void;
  setFillColor: (r: number, g?: number, b?: number) => void;
  text: (
    t: string,
    x: number,
    y: number,
    options?: { align?: "left" | "center" | "right" },
  ) => void;
  rect: (x: number, y: number, w: number, h: number, style?: string) => void;
  line: (x1: number, y1: number, x2: number, y2: number) => void;
  addPage: () => void;
  splitTextToSize: (t: string, w: number) => string[];
  getNumberOfPages: () => number;
  setPage: (n: number) => void;
  save: (name: string) => void;
};

export async function downloadResultsPdf(input: ResultsPdfInput): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" }) as unknown as Doc;

  let y = MARGIN;

  const ensureSpace = (needed: number) => {
    if (y + needed > PAGE_H - MARGIN - 24) {
      doc.addPage();
      y = MARGIN;
    }
  };

  // ── Header ────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text("THEJURY · RESULTS RECORD", MARGIN, y);
  y += 20;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(INK);
  const titleLines = doc.splitTextToSize(input.pollTitle, CONTENT_W);
  for (const line of titleLines) {
    ensureSpace(24);
    doc.text(line, MARGIN, y);
    y += 22;
  }
  y += 2;

  const generated = formatDateFull(input.generatedAt ?? new Date().toISOString());
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(
    `Poll code ${input.pollCode}    ·    ${input.totalVoters} ${
      input.totalVoters === 1 ? "voter" : "voters"
    }    ·    Generated ${generated}`,
    MARGIN,
    y,
  );
  y += 16;

  doc.setDrawColor(RULE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 24;

  // ── Body ──────────────────────────────────────────────────────────────
  if (input.isMultiQuestion && input.questionResults) {
    input.questionResults.forEach((qr, i) => {
      renderQuestionHeading(
        doc,
        `${i + 1}. ${qr.question_text}`,
        ensureSpace,
        () => y,
        (v) => (y = v),
      );
      y = renderQuestionBody(doc, qr, input.totalVoters, y, ensureSpace);
      y += 18;
    });
  } else {
    const rows = input.results ?? [];
    y = renderOptionRows(doc, rows, input.totalVoters, y, ensureSpace);
  }

  // ── Footer on every page ──────────────────────────────────────────────
  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text(
      `Generated by TheJury · Poll ${input.pollCode}`,
      MARGIN,
      PAGE_H - 28,
    );
    doc.text(`Page ${p} of ${pages}`, PAGE_W - MARGIN, PAGE_H - 28, {
      align: "right",
    });
  }

  const date = new Date().toISOString().split("T")[0];
  doc.save(`poll-results-${input.pollCode}-${date}.pdf`);
}

function renderQuestionHeading(
  doc: Doc,
  text: string,
  ensureSpace: (n: number) => void,
  getY: () => number,
  setY: (v: number) => void,
) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(INK);
  const lines = doc.splitTextToSize(text, CONTENT_W);
  for (const line of lines) {
    ensureSpace(18);
    let y = getY();
    doc.text(line, MARGIN, y);
    y += 16;
    setY(y);
  }
}

function renderQuestionBody(
  doc: Doc,
  qr: QuestionResult,
  totalVoters: number,
  y: number,
  ensureSpace: (n: number) => void,
): number {
  const type = qr.question_type || "multiple_choice";

  if (type === "rating_scale" && qr.ratingData) {
    const r = qr.ratingData;
    y = renderKeyValue(doc, "Average rating", r.average.toFixed(2), y, ensureSpace);
    y = renderKeyValue(doc, "Total ratings", String(r.totalRatings), y, ensureSpace);
    y = renderKeyValue(doc, "Scale", `${r.min} – ${r.max}`, y, ensureSpace);
    for (let i = r.min; i <= r.max; i++) {
      const count = r.distribution[i] || 0;
      y = renderBarRow(doc, String(i), count, r.totalRatings, y, ensureSpace);
    }
    return y;
  }

  if (type === "ranked_choice" && qr.rankedData) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    ensureSpace(16);
    doc.text("Option — average position (lower is better) · first-place votes", MARGIN, y);
    y += 16;
    for (const ranked of qr.rankedData) {
      ensureSpace(16);
      doc.setFontSize(10);
      doc.setTextColor(INK);
      const label = doc.splitTextToSize(
        `${ranked.option_text}  —  avg ${ranked.avg_position.toFixed(2)} · ${ranked.first_place_count} first-place`,
        CONTENT_W,
      );
      for (const line of label) {
        ensureSpace(14);
        doc.text(line, MARGIN, y);
        y += 14;
      }
    }
    return y;
  }

  if (type === "open_ended" && qr.openEndedData) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    ensureSpace(16);
    doc.text(`${qr.openEndedData.totalResponses} responses`, MARGIN, y);
    y += 16;
    doc.setFontSize(10);
    doc.setTextColor(INK);
    for (const response of qr.openEndedData.responses) {
      const lines = doc.splitTextToSize(`• ${response}`, CONTENT_W);
      for (const line of lines) {
        ensureSpace(14);
        doc.text(line, MARGIN, y);
        y += 14;
      }
    }
    return y;
  }

  // Standard option-based types
  return renderOptionRows(doc, qr.results, totalVoters, y, ensureSpace);
}

function renderOptionRows(
  doc: Doc,
  rows: PollResult[],
  totalVoters: number,
  y: number,
  ensureSpace: (n: number) => void,
): number {
  for (const row of rows) {
    y = renderBarRow(doc, row.option_text, row.vote_count, totalVoters, y, ensureSpace);
  }
  const total = rows.reduce((s, r) => s + r.vote_count, 0);
  ensureSpace(20);
  doc.setDrawColor(RULE);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 14;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  doc.text("Total votes", MARGIN, y);
  doc.text(String(total), PAGE_W - MARGIN, y, { align: "right" });
  y += 8;
  return y;
}

function renderBarRow(
  doc: Doc,
  label: string,
  count: number,
  denom: number,
  y: number,
  ensureSpace: (n: number) => void,
): number {
  const percentage = pct(count, denom);
  ensureSpace(34);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(INK);
  const labelLines = doc.splitTextToSize(label, CONTENT_W - 120);
  doc.text(labelLines[0], MARGIN, y);
  const valueText = `${count} · ${percentage}%`;
  doc.setTextColor(MUTED);
  doc.text(valueText, PAGE_W - MARGIN, y, { align: "right" });
  y += 8;

  // Bar
  const barH = 6;
  doc.setFillColor(BAR_BG);
  doc.rect(MARGIN, y, CONTENT_W, barH, "F");
  const fillW = Math.max(0, Math.min(1, Number(percentage) / 100)) * CONTENT_W;
  if (fillW > 0) {
    doc.setFillColor(BAR_FILL[0], BAR_FILL[1], BAR_FILL[2]);
    doc.rect(MARGIN, y, fillW, barH, "F");
  }
  y += barH + 16;
  return y;
}

function renderKeyValue(
  doc: Doc,
  key: string,
  value: string,
  y: number,
  ensureSpace: (n: number) => void,
): number {
  ensureSpace(16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(key, MARGIN, y);
  doc.setTextColor(INK);
  doc.text(value, MARGIN + 120, y);
  y += 16;
  return y;
}
